Update contributor ladder
flyteorg/community pull request #15
Opened 2023-06-30 16:55 UTC by davidmirror-ops

In this PR, multiple changes are proposed:

1. Improve the definition of requirements and responsibilities for each role
2. Introduce the Collaborator role, lowering the barrier between the general community and the Contributor privileges
3. Expand the current status of the path to Maintainership

2023-07-01 20:21 UTC, pingsutw approved these changes

2023-07-05 22:37 UTC, cosmicBboy approved these changes

2023-07-06 16:34 UTC, fg91 commented on GOVERNANCE.md
> +        <p>Can create forks</p>
Shouldn't everyone be allowed to create forks? How do you get to a first merged contribution without having created a fork?

2023-07-06 16:35 UTC, fg91 commented on GOVERNANCE.md
> +Collaborators are individuals who demonstrate an active interest on the project and are willing to help other community members.
```suggestion
Collaborators are individuals who demonstrate an active interest in the project and are willing to help other community members.
```

2023-07-06 16:42 UTC, fg91 requested changes
Shouldn't also community members be able to create forks? How could they get their first merged contributions otherwise?

Apart from that LGTM

2023-07-06 18:45 UTC, wild-endeavor commented on GOVERNANCE.md
> +        <p>Can create forks</p>
yeah you can always fork, that's a github thing.  i think this should just say that they should create a fork to create first prs.

2023-07-06 19:33 UTC, davidmirror-ops commented on GOVERNANCE.md
> +Collaborators are individuals who demonstrate an active interest on the project and are willing to help other community members.
Thanks!

2023-07-06 19:35 UTC, davidmirror-ops commented on GOVERNANCE.md
> +        <p>Can create forks</p>
Right, made it a "baseline" privilege for everyone, which is really a GH feature.

2023-07-07 08:45 UTC, bstadlbauer approved these changes
Looks good to me, thank you!

2023-07-11 20:28 UTC, merged